version: '3'

services:
  web:
    build: .
    tty: true
    volumes:
      - ../:/workspace
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: django_sample

  updater:
    image: alpine
    volumes:
      - ./scripts:/scripts
    entrypoint: >
      /bin/sh -c "crontab /scripts/cronjob && crond -f"
    depends_on:
      - db

volumes:
  postgres_data:
